### ISSUE TITLE
`window._webdriver_manualPoll is not a function` on BrowserStack since 8.0.0

### ISSUE THREAD

**Issue by jandockx** [mantoni/mochify.js#238]
I've been running BrowserStack tests with `mochify` for years in the F/OSS project [Toryt Contracts](https://bitbucket.org/toryt/contracts). I just tried to upgrade dependencies, and found that, with my existing definitions in any case, this still works with version `7.1.1`, but fails for all browsers starting from version `8.0.0`.

```
contracts>npm install mochify@8.1.0

> puppeteer@10.1.0 install /Users/…/toryt/contracts/node_modules/puppeteer
> node install.js

Downloading Chromium r884014 - 113.6 Mb [====================] 99% 0.0s 
npm WARN eslint-config-standard@16.0.2 requires a peer of eslint@^7.12.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard-jsx@10.0.0 requires a peer of eslint@^7.12.1 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.

+ mochify@8.1.0
added 2 packages from 1 contributor, removed 130 packages, updated 7 packages and audited 1215 packages in 11.943s

117 packages are looking for funding
  run `npm fund` for details

found 3 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
contracts>npm run wd:osx-chrome

> @toryt/contracts-v@5.0.0 wd:osx-chrome /Users/…/toryt/contracts
> mochify --wd --wd-file .min-wd-osx-chrome.js --async-polling false --reporter dot 'test/**/*Test.js'

build: manual 2021-07-19T09:25:13.577Z
# Chrome - OS X Catalina:
POST /wd/hub/session/ce9637880fbd173f8bcb5d95a7db91d5b6840c41/execute

Unexpected HTTP status: 500 Internal Server Error

server: nginx
date: Mon, 19 Jul 2021 09:25:19 GMT
content-type: application/json; charset=utf-8
content-length: 9479
connection: keep-alive
source-from: 02
expires: Thu, 01 Jan 1970 00:00:00 GMT
cache-control: no-cache, no-cache

Response Status Code: 13
Response Message:
    javascript error: window._webdriver_manualPoll is not a function
      (Session info: chrome=91.0.4472.106)
      (Driver info: chromedriver=91.0.4472.101 (af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}),platform=Mac OS X 10.15.6 x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 11 milliseconds
    Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
    System info: host: 'mac-10-144-144-71.browserstack.com', ip: '10.144.144.71', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.6', java.version: '1.8.0_51'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{mobileEmulationEnabled=false, timeouts={implicit=0, pageLoad=300000, script=30000}, hasTouchScreen=false, platform=MAC, acceptSslCerts=false, goog:chromeOptions={debuggerAddress=localhost:56431}, acceptInsecureCerts=false, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, setWindowRect=true, webauthn:extension:largeBlob=true, unexpectedAlertBehaviour=ignore, applicationCacheEnabled=false, rotatable=false, networkConnectionEnabled=false, chrome={chromedriverVersion=91.0.4472.101 (af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}), userDataDir=/var/folders/3y/zz_w6_s56sl__vcrf3r5bhzr0000hr/T/.com.google.Chrome.F9A1RA}, takesHeapSnapshot=true, pageLoadStrategy=normal, strictFileInteractability=false, databaseEnabled=false, handlesAlerts=true, version=91.0.4472.106, browserConnectionEnabled=false, proxy={}, nativeEvents=true, locationContextEnabled=true, cssSelectorsEnabled=true, webauthn:virtualAuthenticators=true}]
    Session ID: 58d41e96c6c8901d66da09cd9555cf63


Error: Unexpected HTTP status: 500 Internal Server Error

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @toryt/contracts-v@5.0.0 wd:osx-chrome: `mochify --wd --wd-file .min-wd-osx-chrome.js --async-polling false --reporter dot 'test/**/*Test.js'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @toryt/contracts-v@5.0.0 wd:osx-chrome script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/…/.npm/_logs/2021-07-19T09_25_20_928Z-debug.log
j
```

Does anybody have any idea what is wrong?

**Comment by m90** [comment]
This is pretty strange: when you look at the bundled output of your test suite using Mochify 8 (which contains a pre-bundled Mocha 8), there is some transpilation hiccup going on. This portion of the code in the bundled Mocha:

```js
function _unsupportedIterableToArray(o, minLen) {
  if (!o) return;
  if (typeof o === "string") return _arrayLikeToArray(o, minLen);
  var n = Object.prototype.toString.call(o).slice(8, -1);
  if (n === "Object" && o.constructor) n = o.constructor.name;
  if (n === "Map" || n === "Set") return Array.from(o);
  if (n === "Arguments" || /^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n)) return _arrayLikeToArray(o, minLen);
}
```

gets transpiled into:

```js
function _unsupportedIterableToArray(o, minLen) {
  if (!o) return;
  if (typeof o === "string") return _arrayLikeToArray(o, minLen);
  var n = Object.prototype.toString.call(o).slice(8, -1);
  if (n === "Object" && o.constructor) n = o.constructor.name;
  if (n === "Map" || n === "Set") return Array.from(o);
  if (n === "Arguments" || ../../../../^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n)) return _arrayLikeToArray(o, minLen);
}
```

which seems to raise a syntax error on the last line, and which I would assume keeps your tests from evaluating the definition of `_webdriver_manualPoll` . I have zero idea why this is happening though? I can definitely reproduce it though.

More findings:

1. Mochify 7 does not do anything similar as it doesn't contain a bundled version of Mocha and the babel helper snippet is absent.
2. When I use Mochify 8, but instead use the `consolify` option and the look at the output, the transpilation mistake does not happen and the Mocha code gets injected as is.
3. For all versions the client script from min-wd gets injected correctly.

I would assume this is some very unfortunate glitch in bundling, but tbh I have no idea where it is coming from (or if this is the right track even).

**Comment by m90** [comment]
It seems the line in question is being caught by the following RegEx in `lib/trace.js` which is exclusively used when using `--wd`:

https://github.com/mantoni/mochify.js/blob/74dbe2da50bfae0085922d88c01575073734e191/lib/trace.js#L14
```
/^\s+.+:[0-9]+/.test('  if (n === "Arguments" || /^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n)) return _arrayLikeToArray(o, minLen);')
> true
```

which in turn prepends the relative path here: https://github.com/mantoni/mochify.js/blob/74dbe2da50bfae0085922d88c01575073734e191/lib/trace.js#L34

giving us the wonky code. The Regex thinks the line needs to be transformed because a. it has leading whitespace (is indented) and b. it contains `:8`.

To be honest I don't have a clear idea of how to fix this right now, but maybe I don't fully understand what `trace.js` is even doing in that context. Any idea how to solve this @mantoni ?

---

N.B.: I still don't know if this is causing the raised issue btw.

**Comment by m90** [comment]
There seems to be another line in Mocha that accidentally triggers the RE:

```js
    var months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']; // 26 Feb 16:19:34
```

**Comment by m90** [comment]
I'm starting to think I am doing something fundamentally wrong when trying to short circuit the bundling step, treat the above with due skepticism.

**Comment by m90** [comment]
More luck with debugging the issue this time: this seems to happen once mocaccino is using the rollupified bundle of Mocha that was introduced in Mocha 8.1.0. When you forcefully downgrade mocaccino to use Mocha 8.0.0 it seems to work as expected, upgrading it back to 8.1.0 breaks it, creating the `window._webdriver_manualPoll is not a function` error. (at least the bundling https://github.com/mochajs/mocha/pull/4293 is what I would expect to be the culprit as everything else seems to be pretty unsuspicious: https://github.com/mochajs/mocha/releases/tag/v8.1.0)

I still have no idea why this is creating a problem in the WebDriver context though: when bundling the test output of `min-wd` and loading it up in a real browser, `window._webdriver_manualPoll` and siblings will be present and callable.
